### ISSUE TITLE
PA Review - Auth

### ISSUE THREAD

**Issue by c-noonan** [c-noonan/AirBnweee#2]
- [x] Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x]  Presentational Components
 - [x] Styling
 - [x]  Smooth, bug-free navigation
 - [x]  Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
It looks great! The only major part left is:
- [x] Clear errors when the form switches.

A few small points:
- [x] The border on the session buttons is curved. Since we do want to keep them semantically as buttons, you can fix this with `border-radius`.
- [x] The icons are great! Maybe switch the email with a person figure for `username`. 
- [x] The `x` button is not clickable to close the modal.

Optional:
- [ ] Add a Welcome message to the form.
- [ ] Figure out how to transform the size of the modal depending on content instead of hard coding the height and width.
