### ISSUE TITLE
PA Review - Spots

### ISSUE THREAD

**Issue by c-noonan** [c-noonan/AirBnweee#4]
- [x] Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x] Presentational Components
 - [x] Styling
 - [x] Smooth, bug-free navigation
 - [x] Adequate and appropriate seeds
 - [x] Spots have a cohesive home page with picture and description

**Comment by anastassia-b** [comment]
Great start! Based on our discussion today:

- [x] Today's priority is to build the spots index page with spot index items.
- [x] Initial seed of the database with 3 theme parks and 8 spots each. Google maps will be centered in southern California.

For MVPs, only fetching pre-seeded spots is required. The full CRUD cycle for a user's spots can be bonus.

**Comment by anastassia-b** [comment]
Awesome work! In order to complete this MVP please finish the following:

- [x] The seed data in heroku seems to be a bit duplicated from prior seedings. Ensure you have a `Class.destroy_all` for each model. I would also wrap your seeds in an `ActiveRecord::Base.transaction` to ensure they are all pass or all fail through together. 
- [x] Link each spot index item to the spot show page 
- [x] Finalize the spot show page with styling (just without reviews and reservations).
- [x] the `.list-elements img` warps aspect ratio when the window size changes.
- [x] Google maps needs to be implemented, showing the spots with their locations as markers.

Later, you might think about how to increase interconnectivity in your site. For example, from the spots index results, clicking a spot could open a large Modal with the spot information, so that the user can close it and remain on the results page. Airbnb solved this by opening a new tab, so this might feel even nicer than that. A separate spot show page is also important to have, for when you want to link to it directly.

**Comment by anastassia-b** [comment]
Great, you were able to refactor the spots show as a separate page, while keeping the essential information in the modal. I think this helps your site be really interconnected. This MVP is complete!
