### ISSUE TITLE
PA Review - Reviews

### ISSUE THREAD

**Issue by c-noonan** [c-noonan/AirBnweee#6]
- [x] Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x] Presentational Components
 - [x] Styling
 - [x] Smooth, bug-free navigation
 - [x] Adequate and appropriate seeds to demonstrate the feature
 - [x] Users can leave reviews; reviews can have comments, ratings, and dates

**Comment by c-noonan** [comment]
Should reviews include a rating and date? Or make that secondary characteristic?

**Comment by anastassia-b** [comment]
Good question. Based on your database schema, a review knows its `user_id` and its `spot_id`. If you wanted to easily fetch the dates of the stay, you could have reviews belong_to a booking (just keep track of a `booking_id`). Either way would work (your associations would just be a little different). The body and the rating are definitely primary though. 

In a fully-functioning site, the ideal architecture would be to only allow a user to review a spot if there is booking. While more "correct", it wouldn't show off all the responsiveness this project is capable of showing (with being able to leave a review on any spot anytime). So, whichever way you decide to implement it, be able to defend your design decisions with respect to the goals of this project.

**Comment by anastassia-b** [comment]
Based on our meeting today, you refactored your review slice of state to include the basic reviewer information required for rendering. In order to complete this MVP: 

- [x] Display reviews on each spot show page.
- [x] Under/Above the review list, have a review form for adding your own. 
- [x] Ensure that only a logged in user can leave a review. 
- [x] A user can edit and delete their own review.

**Comment by c-noonan** [comment]
All finished!
